"""Add auth tracking fields

Revision ID: 13bfa4eb853e
Revises: 5bbd7b62dcc3
Create Date: 2026-08-16 19:02:32.688858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bfa4eb853e'
down_revision = '5bbd7b62dcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sessions_valid_after', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sessions_valid_after')
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###
